[package]
name = "api-gateway"
version.workspace=true
edition.workspace=true

[dependencies]
actix-web.workspace=true
actix-ws.workspace=true
tokio-stream.workspace=true
redis = { workspace = true, features = ["tokio-comp"] }

tokio.workspace=true
tracing.workspace=true
serde.workspace=true
serde_json.workspace=true
uuid.workspace=true
chrono.workspace=true
futures-util.workspace=true
rust_decimal.workspace=true
tonic.workspace=true
prost.workspace=true
proto = { path = "../../crates/proto" }
async-trait.workspace=true
sqlx.workspace = true
rdkafka.workspace=true
wtransport.workspace=true
anyhow.workspace=true
database = { path = "../../crates/database" }

telemetry = { path = "../../crates/telemetry" }
config = { path = "../../crates/config" }
errors = { path = "../../crates/errors"}
