[package]
name = "chart-service"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true }
tonic = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
rdkafka = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
futures-util = { workspace = true }
redis = { workspace = true, features = ["tokio-comp"] }

database = { path = "../../crates/database" }
config = { path = "../../crates/config" }
errors = { path = "../../crates/errors" }
telemetry = { path = "../../crates/telemetry" }
proto = { path = "../../crates/proto" }