[package]
name = "matching-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
anyhow.workspace = true
uuid.workspace = true
rust_decimal.workspace = true
chrono.workspace = true
rdkafka.workspace = true
futures-util = "0.3"
tonic.workspace = true
prost.workspace = true
async-trait.workspace = true
dashmap = "6"
bincode.workspace = true
mimalloc.workspace = true
rustc-hash.workspace = true

proto = { path = "../../crates/proto" }
config = { path = "../../crates/config" }
telemetry = { path = "../../crates/telemetry" }

[[bin]]
name = "kafka-load-tester"
path = "src/bin/kafka_load_tester.rs"
