app_name = "Account Service"

[server]
host = "127.0.0.1"
port = 8083

[grpc]
host = "127.0.0.1"
port = 50053

[database]
host = "localhost"
port = 5432
username = "postgres"
password = "postgres"
database = "perps_accounts"
auto_migrate = true
