app_name = "Chart Service"

[server]
host = "127.0.0.1"
port = 8088

[database]
host = "127.0.0.1"
port = 5433
database = "perps_charts"
username = "postgres"
password = "postgres"
auto_migrate = true

[redis]
host = "127.0.0.1"
port = 6379

[grpc]
host = "127.0.0.1"
port = 50058
