app_name = "Risk Engine Service"
environment = "development"

[server]
host = "127.0.0.1"
port = 8087

[grpc]
host = "127.0.0.1"
port = 50057

# [kafka]
# brokers = ["127.0.0.1:9092"]

[database]
host = "localhost"
port = 5432
username = "postgres"
password = "postgres"
database = "perps_risk"
auto_migrate = true

[redis]
host = "127.0.0.1"
port = 6379
