[package]
name = "oracle-aggregator"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
rdkafka = { workspace = true }
redis = { workspace = true, features = ["tokio-comp"] }

tokio-tungstenite = { workspace = true }
futures-util = "0.3"
anyhow = { workspace = true }
tracing = { workspace = true }
telemetry = { path = "../../crates/telemetry" }
config = { path = "../../crates/config" }
errors = { path = "../../crates/errors" }
sqlx = { workspace = true }
rust_decimal = { workspace = true }
async-trait = { workspace = true }
proto = { path = "../../crates/proto" }
tonic = { workspace = true }