CREATE TABLE IF NOT EXISTS accounts(
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL,
    asset VARCHAR(16) NOT NULL,
    balance NUMERIC(38, 18) NOT NULL DEFAULT 0,
    frozen NUMERIC(38, 18) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP

);


CREATE UNIQUE INDEX IF NOT EXISTS idx_user_asset ON accounts (user_id, asset);
